import ServerProvider from "@/components/providers/server-provider/ServerProvider";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider/ThemeProvider";
import AppBar from "@/components/product/app-bar/AppBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ServerProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
            disableTransitionOnChange
          >
            <AppBar />
            <section className="container max-w-5xl py-4">{children}</section>
          </ThemeProvider>
        </ServerProvider>
      </body>
    </html>
  );
}
